USE graphql_practice;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS User;
CREATE TABLE User(
  id INT AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  PRIMARY KEY(id)
);
DESC User;
CREATE TABLE Post(
  id INT AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL,
  author_id INT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(author_id) REFERENCES User(id) ON DELETE CASCADE
);
DESC Post;
CREATE TABLE Comment(
  id INT AUTO_INCREMENT,
  text VARCHAR(255) NOT NULL,
  author_id INT NOT NULL,
  post_id INT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(author_id) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY(post_id) REFERENCES Post(id) ON DELETE CASCADE
);
DESC Comment;